### PR TITLE
Fix terminal color on Windows

### LINKED ISSUE #175: Console log color missing since Leaf a3f3dba
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

Console log color is missing

### Expected behaviour

Logs are colored correctly

### To Reproduce

1. Install any plugins that print colored console logs(e.g. LuckPerms)
2. Launch the server
3. Colors are missing

### Spark profiler link

https://spark.lucko.me/WSH7RyMDtr

### Error log (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by Dreeam-qwq**
Windows doesn't have environment variables TERM and COLORTERM by default, but we assuming that it supports the `truecolor` for terminal.

## Welcome to test it on:

- Java 21 and Java 22

and,

- Windows, Linux, Pterodactyl panel or MSCM panel.

Things to test:
- Whether has color
- Whether can input words/commands in console smoothly
- Whether has https://github.com/Winds-Studio/Leaf/issues/73 issue on panel (Don't add  `-Dterminal.jline=false` and `-Dterminal.ansi=true`)

**Test Jar: [Leaf 1.21.1.zip](https://github.com/Winds-Studio/Leaf/actions/runs/12093416555/artifacts/2255994416)**

Tested on my side that all can work fine.

### CODE REVIEW

**Comment by MC-XiaoHei** [comment]
Test on Windows 11 Canary 27754.1000
Java Info:
```
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
```
Test 1, 2 passed.

**Comment by Kotori0629** [comment]
a24768e496207b19655d77dc11bef902
container@pterodactyl~ java -version
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -Xmx12288M -XX:MaxRAMPercentage=95.0 -Duser.timezone=Asia/Shanghai -Dfile.encoding=UTF-8 -Dlog4j2.formatMsgNoLookups=true -jar server.jar

Tested on Pterodactyl, it worked

**Comment by kidofcubes** [comment]
image
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7)
OpenJDK 64-Bit Server VM (build 21.0.4+7, mixed mode, sharing)

works on linux

**Comment by HaHaWTH** [comment]
Env: Java 21 (Java HotSpot(TM) 64-Bit Server VM 21.0.4+8-LTS-jvmci-23.1-b41; Oracle Corporation Oracle GraalVM 21.0.4+8.1) on Windows 10 10.0 (amd64)
IMG_5440

**Pull request merged**
