### PR TITLE
[Dev] Async features

### PR DESCRIPTION
**Pull request by Dreeam-qwq**
This pr added some async features for Leaf, based on the latest commit of ver/1.21.1 branch.
Active testing now, report (just leave comments below) any issues related to them.

Download test Jar for this pr: [Leaf 1.21.1 #109 - c0effa6](https://github.com/Winds-Studio/Leaf/actions/runs/10729275041/artifacts/1898784200)

---

- Async entity tracker
        Some issues needs to test to see if them still exist and improvements :
     - [x] Visible issue related with NPC (plugins like Citizens) (see Bloom-host / Petal issue 3)
     - [x] Move items in shulker box cause disconnect (see Bloom-host / Petal issue 11)
     - [x] Optimize tracker, to reduce execute time.
     - [x] Add compat mode, move Citizens compat logic into it.

- Async playerdata saving
     - [x] Will not cause player data lost

## Disclaimer: It's not save to use it in producation for now.

### CODE REVIEW

**Comment by QuQuShKa1205** [comment]
Here is the log with different errors.  https://mclo.gs/znMTK0g. Hope it helps a little bit.

**Comment by Dreeam-qwq** [comment]
> Here is the log with different errors. https://mclo.gs/znMTK0g. Hope it helps a little bit.

Thanks, but it’s more like an AdvancedChat plugin issue

**Comment by PythonChicken123** [comment]
I also tried this and many plugins caused errors while using this test Jar:

**Leaf Jar**: leaf-1.21.1-reobf.jar from [Leaf 1.21.1 #109](https://github.com/Winds-Studio/Leaf/actions/runs/10535014348/artifacts/1849608655)
**Spark Profiler**: https://spark.lucko.me/RLiiqnxNDh
**ViaVersion Dump**: https://dump.viaversion.com/e824282a40cfc54b94d4a635433bbc64a1fa785102a966412248dbf890670e7f
**Plugins (Some are outdated)**: 
```
[12:22:12 INFO]: [PluginInitializerManager] Initialized 83 plugins
[12:22:12 INFO]: [PluginInitializerManager] Paper plugins (2):
 - AdvancedKits (1.17.19), RoseStacker (1.5.25)
[12:22:12 INFO]: [PluginInitializerManager] Bukkit plugins (81):
 - AdvancedChat (1.4.0), AdvancedChests (40.9), AdvancedCrates (4.0.10), AdvancedEnchantments (9.10.6), AntiPopup (9.2), AuthMe (5.7.0-FORK-b53), BedrockParity (2.0.2), BetterRTP (3.6.13), BetterTeams (4.10.0), CMI (9.7.5.4), CMIEInjector (1.0.2.4), CMILib (1.5.1.1), CSuggestion (1.0.1), Chunky (1.4.10), ChunkyBorder (1.2.13), Citizens (2.0.35-SNAPSHOT (build 3493)), CommandPrompter (2.10.0), CustomFishing (2.2.18), DailyRewardsPlus (1.4.0), DecentHolograms (2.8.11), DeluxeCoinflip (2.7.13), DeluxeCombat (1.60.7), DeluxeMenus (1.14.1-DEV-184), DeluxeTags (1.8.3-DEV-23), DeluxeWithdraw (2024.07), DeluxeWithdrawLifestealCoreAddon (2024.07), FastAsyncWorldEdit (2.11.2-SNAPSHOT-883;a64e09a), FastCraft (3.2.13), FastTP (1.0), FasterCrystals (1.8.0), GangsPlus (2.33.0), Geyser-Spigot (2.4.2-SNAPSHOT), GeyserExtras (1.21.0-v1.1.4), HeadDatabase (4.19.8), ItemsAdder (4.0.2-alpha-test-3), JetsAntiAFKPro (3.8.4), Jobs (5.2.4.2), KixsChatGames (2.1.7), LPX (3.4.8), LibsDisguises (10.0.44-SNAPSHOT), LifestealCore (2024.07-a), LightOptimizer (1.9), LiteBans (2.15.1), LoneLibs (1.0.56), LuckPerms (5.4.139), Matrix (7.9.21A), Multiverse-Core (4.3.12), NBTAPI (2.13.2), PinataParty (2.67.0), PlaceholderAPI (2.11.7-DEV-200), PlayerVaults (4.3.1), PremiumVanish (2.9.13), ProtocolLib (5.3.0-SNAPSHOT-726), RayTraceAntiXray (1.15.0), RoseLoot (1.2.17), ShopGUIPlus (1.97.1), SkBee (3.6.1), SkQuery (4.1.10), Skript (2.9.1), TAB (4.1.7), TimerFix (1.0), UltimateAutoRestart (2024.07), UpgradeableSpawners (4.14.8), Vault (1.7.3-CMI), ViaBackwards (5.0.4-SNAPSHOT), ViaVersion (5.0.4-SNAPSHOT), VirtualBounty (1.0), VoidGen (2.2.1), Votifier (2.7.3), Vulcan (2.9.0), WorldGuard (7.0.11-SNAPSHOT+2287-8ffc81a), WorldGuardExtraFlags (4.2.4-SNAPSHOT), WorldGuardRegionProtect (1.0.4.21), eco (6.73.5), floodgate (2.2.3-SNAPSHOT (b197-e4c47aa)), packetevents (2.5.0+97fee0c89-SNAPSHOT), skRayFall (1.9.28), skript-placeholders (1.6.0), skript-reflect (2.5.1), zAuctionHouseV3 (3.2.2.4), zMenu (1.0.3.4)
```
**Server Log**: https://mclo.gs/AH7QJTX

### Final Words
I am currently using the reobf jar, next time, I will send an another report using the mojmap jar and updating all plugins that I have currently in my server. I also wanted to join my server but I got no response from the server or even in the logs and I checked that it is not a firewall issue. I'll look into that. I hope this helps you aswell. :)

**Comment by TheWylot** [comment]
Nice job!

**Pull request merged**
